# Generated by Django 2.2.5 on 2019-10-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название поставщика')),
                ('url', models.CharField(max_length=100, verbose_name='Url адрес API')),
                ('headers', models.CharField(max_length=100, verbose_name='Заголовок запроса')),
                ('data', models.TextField(verbose_name='Тело запроса')),
            ],
            options={
                'verbose_name': 'Настройки API',
                'verbose_name_plural': 'Настройки API',
            },
        ),
        migrations.AlterField(
            model_name='producttype',
            name='partner1',
            field=models.CharField(max_length=10, verbose_name='Название у партнера (OCS)'),
        ),
    ]
