# Generated by Django 2.2.5 on 2019-10-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191021_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapi',
            name='catalog',
            field=models.TextField(default='', verbose_name='Запрос каталога'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='providerapi',
            name='data',
            field=models.TextField(verbose_name='Запрос цены'),
        ),
    ]
