# Generated by Django 2.2.5 on 2019-10-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_producttype_partner2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', models.CharField(max_length=20, verbose_name='Артикул производителя')),
                ('name', models.TextField(verbose_name='Описание')),
                ('id_1c', models.CharField(max_length=20, verbose_name='Артикул в 1с')),
                ('id_partner1', models.CharField(max_length=20, verbose_name='Артикул в OCS')),
                ('id_partner2', models.CharField(max_length=20, verbose_name='Артикул в Treolan')),
            ],
            options={
                'verbose_name': 'Еденица товара',
                'verbose_name_plural': 'Таблица товаров',
            },
        ),
    ]
