# Generated by Django 2.1.13 on 2019-10-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='id_1c',
            field=models.CharField(blank=True, max_length=20, verbose_name='Артикул в 1с'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='id_partner1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Артикул в OCS'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='id_partner2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Артикул в Treolan'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='partner1',
            field=models.CharField(blank=True, max_length=10, verbose_name='Название у партнера (OCS)'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='partner2',
            field=models.CharField(blank=True, max_length=40, verbose_name='Название у партнера (Treolan)'),
        ),
        migrations.AlterField(
            model_name='providerapi',
            name='catalog',
            field=models.TextField(blank=True, verbose_name='Запрос каталога'),
        ),
        migrations.AlterField(
            model_name='providerapi',
            name='data',
            field=models.TextField(blank=True, verbose_name='Запрос цены'),
        ),
        migrations.AlterField(
            model_name='providerapi',
            name='headers',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок запроса'),
        ),
    ]
