# Generated by Django 2.1.13 on 2019-12-12 22:11

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mapping_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_1c', models.CharField(blank=True, max_length=10, verbose_name='Код в 1с')),
                ('id_ocs', models.CharField(blank=True, max_length=50, verbose_name='Код в OCS')),
                ('id_treolan', models.CharField(blank=True, max_length=250, verbose_name='Код в Treolan')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.Catalog')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Остаток')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Цена и остатки',
                'verbose_name_plural': 'Цены и остатки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Описание')),
                ('partnumber', models.CharField(max_length=20, verbose_name='Артикул производителя')),
                ('id_1c', models.CharField(blank=True, max_length=20, verbose_name='Артикул в 1с')),
                ('id_ocs', models.CharField(blank=True, max_length=20, verbose_name='Артикул в OCS')),
                ('id_treolan', models.CharField(blank=True, max_length=20, verbose_name='Артикул в Treolan')),
                ('catalog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Catalog')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Еденицы измерения')),
                ('id_treolan', models.CharField(blank=True, max_length=20, verbose_name='id в Treolan')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
            },
        ),
        migrations.CreateModel(
            name='Property_Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Значение')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Property')),
            ],
            options={
                'verbose_name': 'Значение свойства',
                'verbose_name_plural': 'Значения свойст',
            },
        ),
        migrations.AddField(
            model_name='price',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='price',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProviderAPI'),
        ),
    ]
