# Generated by Django 2.1.13 on 2019-12-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191213_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapi',
            name='detail_info',
            field=models.TextField(blank=True, verbose_name='Запрос подробной информации'),
        ),
        migrations.AlterField(
            model_name='price',
            name='balance',
            field=models.CharField(max_length=10, verbose_name='Остаток'),
        ),
    ]
