# Generated by Django 2.1.13 on 2019-12-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191218_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapi',
            name='detail_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Url подробной информации'),
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
