# Generated by Django 2.1.13 on 2020-01-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200121_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Catalog')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Property')),
            ],
            options={
                'verbose_name': 'Значение свойства',
                'verbose_name_plural': 'Значения свойст',
            },
        ),
    ]
