# Generated by Django 2.1.13 on 2020-01-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_importantproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importantproperty',
            options={'verbose_name': 'Свойство', 'verbose_name_plural': 'Свойства для экспорта'},
        ),
        migrations.AddField(
            model_name='catalog',
            name='export',
            field=models.BooleanField(default=False, verbose_name='Можно экспортировать'),
        ),
    ]
