# Generated by Django 2.2.9 on 2020-02-07 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200121_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', related_query_name='price', to='main.Product'),
        ),
    ]
