# Generated by Django 2.2.9 on 2020-02-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200207_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='partnumber',
            field=models.CharField(max_length=50, verbose_name='Артикул производителя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='partnumber',
            field=models.CharField(max_length=50, verbose_name='Артикул производителя'),
        ),
    ]
