# Generated by Django 2.2.9 on 2020-02-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200207_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog_mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50, verbose_name='Код поставщика')),
            ],
            options={
                'verbose_name': 'ИД производителя',
                'verbose_name_plural': 'Таблица соответсвия каталогов',
            },
        ),
        migrations.CreateModel(
            name='Product_mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50, verbose_name='Код поставщика')),
            ],
            options={
                'verbose_name': 'ИД производителя',
                'verbose_name_plural': 'Таблица соответсвия товаров',
            },
        ),
        migrations.CreateModel(
            name='Property_mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50, verbose_name='Код поставщика')),
            ],
            options={
                'verbose_name': 'ИД производителя',
                'verbose_name_plural': 'Таблица соответсвия свойств',
            },
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='id_1c',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='id_ocs',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='id_treolan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id_1c',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id_ocs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id_treolan',
        ),
        migrations.RemoveField(
            model_name='property',
            name='id_treolan',
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[(1, 'basic'), (2, 'personal'), (3, 'Изображение')], default=2, max_length=1, verbose_name='Тип свойства'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Catalog'),
        ),
        migrations.AlterField(
            model_name='property_value',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='main.Product'),
        ),
        migrations.DeleteModel(
            name='Mapping',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.AddField(
            model_name='property_mapping',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_ids', to='main.Property'),
        ),
        migrations.AddField(
            model_name='property_mapping',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProviderAPI'),
        ),
        migrations.AddField(
            model_name='product_mapping',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_ids', to='main.Product'),
        ),
        migrations.AddField(
            model_name='product_mapping',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProviderAPI'),
        ),
        migrations.AddField(
            model_name='catalog_mapping',
            name='catalog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_ids', to='main.Catalog'),
        ),
        migrations.AddField(
            model_name='catalog_mapping',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProviderAPI'),
        ),
    ]
