# Generated by Django 2.2.9 on 2020-02-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200210_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_value',
            name='local_value',
            field=models.TextField(blank=True, verbose_name='Внутренне значение'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('1', 'basic'), ('2', 'personal'), ('3', 'Изображение')], max_length=1, verbose_name='Тип свойства'),
        ),
    ]
